name: CICD-Deploy-AWS-S3Bucket
env:
  AWS_S3_BUCKET_NAME: "git-actions-devops"
  AWS_REGION_NAME   : "eu-central-1"

on:
  push:
    branches: 
      - master

jobs:
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone Git Repository
      uses: actions/checkout@v1
      
    - name: Check Position
      run : pwd
      
    - name: List Directory
      run : ls -al
      
    - name: AWS VERSION
      run : aws --version
    
    - name: AWS AUTHENFICATION
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
    
    - name: DEPLOY TO AWS S3 BUCKET
      run: aws s3 sync . s3://git-actions-devops 
      
      
      
      
      
      
      
      
      
      
